from pytrebuchet.differential_equations.free_flight_phase import free_flight_ode, projectile_hits_ground_event
from pytrebuchet.differential_equations.sling_phase import sling_projectile_ode, projectile_release_event
from pytrebuchet.differential_equations.sliding_phase import sliding_projectile_ode, ground_separation_event