name: CI
on: [push, pull_request]
jobs:
   
  ruff:
    name: Ruff Linter
    runs-on: ubuntu-latest
    steps:
      - uses: astral-sh/ruff-action@v3
        with:
          args: check .
          src: "."
